---
title: 'my_ipm_report'
output:
  html_document:
    toc: true
    toc_depth: 3
date: '`r Sys.Date()`'
urlcolor: blue
header_includes:
  - \usepackage{amsmath}
---


## IPM Iteration Expressions

These expressions iterate the IPM. Check translations from R code to Latex for accuracy before distributing! If needed, edit the _Rmd_ file directly. It can be found here: `C:/Artigos e resumos publicados submetidos ideias/Notes/9 - ITV/Dados-scripts-ITV/Daphnopsis-Dados-e-scripts/ipmr_report_20250127.Rmd`


$$n(dbh', t + 1) = \int_{L_{dbh}}^{U_{dbh}}[P]n(dbh, t)ddbh + \\ \int_{L_{dbh}}^{U_{dbh}}[F]n(dbh, t)ddbh\tag{1.1}$$


$$P(dbh', dbh) = s * g\tag{1.2}$$


$$F(dbh', dbh) = r\_r * r\_s * r\_d\tag{1.3}$$



## IPM Vital Rate Expressions

These expressions generate the vital rates the IPM. Check  translations from R code to Latex for accuracy before distributing!


$$s = \frac{1}{\left(1 + e^{ - \left(s\_int + s\_slope * \\ dbh\right)}\right)}\tag{2.1}$$


$$g = Norm(dbh' | g\_mu, g\_sd)\tag{2.2}$$


$$g\_mu = g\_int + g\_slope * dbh\tag{2.3}$$


$$r\_r = \frac{1}{\left(1 + e^{ - \left(r\_r\_int + r\_r\_slope * \\ dbh\right)}\right)}\tag{2.4}$$


$$r\_s = e^{r\_s\_int + r\_s\_slope * dbh}\tag{2.5}$$


$$r\_d = Norm(dbh' | r\_d\_mu, r\_d\_sd)\tag{2.6}$$



## Implementation Details

### Parameter values

The following parameter values were used to implement this IPM: 


  - s\_int = -3

  - s\_slope = 0.5

  - g\_int = 0.1

  - g\_slope = 1.033

  - g\_sd = 2.2

  - r\_r\_int = -5

  - r\_r\_slope = 0.1

  - r\_s\_int = -3

  - r\_s\_slope = 0.03

  - r\_d\_mu = 1.2

  - r\_d\_sd = 0.7


### Domains and Integration Rules

The following domains and integration rules were used to implement this IPM: 


  - $dbh = [L_{dbh} = 1, U_{dbh} = 30], n_{dbh} = 30$

 where $n_{x}$ denotes the number of meshpoints for the midpoint rule for integration.
